### ISSUE TITLE
update KDE runtime to 5.15

### ISSUE THREAD

**Issue by eszlari** [flathub/org.fdroid.Repomaker#4]

**Comment by AltNico** [comment]
[Work on this has already started](https://gitlab.com/fdroid/fdroid-repomaker-flatpak/merge_requests/29), but unfortunately we're stuck at an older version of a dependency which won't let us update to the newer python version of 5.12.

**Comment by eszlari** [comment]
You could bundle the specific python version you need.

**Comment by eszlari** [comment]
5.11 is EOL: https://github.com/KDE/flatpak-kde-runtime/commit/4d7a8d72983d9e86f5f5ce46d3524544c0ee6abe

**Comment by AltNico** [comment]
Turns out that the bug that broke python 3.7 support was fixed in our LTS branch of Django, too: https://github.com/django/django/pull/10654

Therefore we'll update to 5.12 soon.

**Comment by mbooth101** [comment]
Any update on this? This is required in order to move to a modern version of OpenJDK (see #5) -- the version you are currently using is considered EOL by upstream OpenJDK project and is no longer receiving updates or security fixes.

**Comment by AltNico** [comment]
Quoting from https://github.com/flathub/org.fdroid.Repomaker/issues/5#issuecomment-541010601:

> Half a year ago, I tried to fix all this mess ([repomaker!213](https://gitlab.com/fdroid/repomaker/merge_requests/213), [repomaker!215](https://gitlab.com/fdroid/repomaker/merge_requests/215)), but sadly I'm quite limited in time these days and therefore couldn't finish it. I've urged other F-Droid people in internal chats of F-Droid to proceed on this and we're currently discussing how to proceed on this. The main thing is lack of volunteers and thereby lack of maintenance.

The reason I couldn't update our runtime was, if I remember correctly, due to the upgrade of Python which broke either Django or fdroidserver. To explain: The old version of Django blocks the update to newer versions of Python which blocks the update of our Flatpak runtime which blocks our update of Java which blocks our update of fdroidserver... We're essentially running in circles here.

Again from https://github.com/flathub/org.fdroid.Repomaker/issues/5#issuecomment-541010601:

> I'll come back to you the next days with news on how we want to proceed.
