### ISSUE TITLE
Please update to at least openjdk11

### ISSUE THREAD

**Issue by mbooth101** [flathub/org.fdroid.Repomaker#5]
This application is the only one left in Flathub that still uses openjdk9. This JDK has been deprecated for a long long time and was just [EOL'd in Flathub](https://raw.githubusercontent.com/flathub/org.freedesktop.Sdk.Extension.openjdk9/master/flathub.json)

The current LTS release of OpenJDK is 11, please switch to that version at the very least:

https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11

This also depends on adopting an updated KDE as described in #4 because KDE 5.11 is too old to support this version OpenJDK (A.K.A the base freedesktop platform version of 1.6 is too old/also EOL)

**Comment by AltNico** [comment]
Hey @mbooth101,

thanks for notifying us. I'm sorry to hear we're the last one making troubles.

Half a year ago, I tried to fix all this mess ([repomaker!213](https://gitlab.com/fdroid/repomaker/merge_requests/213), [repomaker!215](https://gitlab.com/fdroid/repomaker/merge_requests/215)), but sadly I'm quite limited in time these days and therefore couldn't finish it. I've urged other F-Droid people in internal chats of F-Droid to proceed on this and we're currently discussing how to continue with this. The main thing is lack of volunteers and thereby lack of maintenance.

We can't upgrade to openjdk11 currently because it's blocked by the KDE runtime (#5).

I'll come back to you the next days with news on how we want to proceed.

Thanks for your patience!

**Comment by mbooth101** [comment]
@AltNico No worries, if you need any help for anything Java related, I am happy to lend a hand :-)

**Comment by AltNico** [comment]
@mbooth101 I just created [gitlab/fdroid/repomaker#124 Looking for new maintainers of Repomaker](https://gitlab.com/fdroid/repomaker/issues/234) which we'll also share in social networks. Hopefully we find someone to continue maintenance of Repomaker.

**Comment by AltNico** [comment]
To give you all an update here: our call for help in the fediverse was quite successful, as we now have two people interested in Repomaker. One of them is already working actively on upgrading Django in [gitlab/fdroid/repomaker!218](https://gitlab.com/fdroid/repomaker/merge_requests/218) which is one of the blocker of #4 which is blocking this issue.

**Comment by mbooth101** [comment]
Nice \ó/

**Comment by eighthave** [comment]
fix is here https://gitlab.com/fdroid/fdroid-repomaker-flatpak/-/merge_requests/32
