### ISSUE TITLE
the latest tag here is 1.0.0b2, but on flathub.org, its still 1.0.0b1

### ISSUE THREAD

**Issue by eighthave** [flathub/org.fdroid.Repomaker#7]
It seems that Repomaker is re-enabled on flathub.org, but not for the latest version:
https://flathub.org/apps/details/org.fdroid.Repomaker

This repo's latest tag is `1.0.0b2`: 
https://github.com/flathub/org.fdroid.Repomaker/releases/tag/1.0.0b2

Is there something that checks the GPG signature of the git tag?  The new tag has a different signer (@AltNico signed .0.0b1 and I signed 1.0.0b2).

@cpba could you help me understand what's happening here?
@fabiola.maurice @n8fr8

**Comment by AltNico** [comment]
@eighthave I could imagine that although the Git repo got unarchived, 
the builds didn't get enabled.

Flathub doesn't care about Git tags iirc but always builds and ships 
latest `master` of this Git repo. That's why I kept the other repo on 
gitlab.com, to not mistakenly push to `master` and ship a non-production 
version.

**Comment by cpba** [comment]
It's all working properly and the version is indeed the latest.

It only shows up as an earlier version because we have a silly bug in the manifest.

I've created a merge request to fix it:

https://gitlab.com/fdroid/fdroid-repomaker-flatpak/-/merge_requests/35

**Comment by eighthave** [comment]
Merged in bd6251f29f36bbaf8ac4ac6e9ba64d0c9201d965 and pushed to github.  Since the tags are not part of this process, I deleted them.
